version: '3'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    front-end:
        image: python:3
        restart: always
        ports:
            - 8080:5000

