version: '3.1'
services:
        mongo:
                image: mongo
                restart: always
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: example
                ports:
                        - 27017:27017
                volumes:
                        - /mnt/magfin/mongo/datadir:/data/db

        dbint:
                image: kchan/magfin_dbinterface:dev
                ports:
                        - 8080:8080
                depends_on:
                        - mongo
                command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
